# Generated by Django 3.1.1 on 2020-09-24 12:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webapp_id', models.IntegerField()),
                ('webapp_logo', models.ImageField(blank=True, upload_to='web-defaults/')),
                ('webapp_name', models.CharField(max_length=200)),
                ('webapp_owner', models.CharField(blank=True, max_length=100)),
                ('footer', models.CharField(blank=True, max_length=512)),
                ('footer_url', models.CharField(blank=True, max_length=512)),
                ('footer2', models.CharField(blank=True, max_length=512)),
                ('footer2_url', models.CharField(blank=True, max_length=512)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('tagline', models.TextField()),
                ('writeup', models.TextField()),
                ('sub_title1', models.CharField(max_length=512)),
                ('sub_title2', models.CharField(max_length=512)),
                ('video_provider', models.CharField(blank=True, max_length=512)),
                ('video_meet_host', models.CharField(blank=True, max_length=512)),
                ('activation_key', models.CharField(blank=True, max_length=50)),
                ('activation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('expiration_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='web-promotion/')),
                ('name', models.TextField()),
                ('name2', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('webapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.webapp')),
            ],
        ),
        migrations.CreateModel(
            name='Feature2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='web-feature2/')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('label1', models.CharField(blank=True, max_length=250)),
                ('label2', models.CharField(blank=True, max_length=250)),
                ('label3', models.CharField(blank=True, max_length=250)),
                ('webapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.webapp')),
            ],
        ),
        migrations.CreateModel(
            name='Feature1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='web-feature1/')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('label1', models.CharField(blank=True, max_length=250)),
                ('label2', models.CharField(blank=True, max_length=250)),
                ('label3', models.CharField(blank=True, max_length=250)),
                ('webapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.webapp')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='web-banner/')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('label1', models.CharField(blank=True, max_length=250)),
                ('label2', models.CharField(blank=True, max_length=250)),
                ('label3', models.CharField(blank=True, max_length=250)),
                ('webapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.webapp')),
            ],
        ),
    ]
