# Generated by Django 3.1.1 on 2020-09-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_promotion_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='sequence',
        ),
    ]
