# Generated by Django 3.1.1 on 2020-09-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_promotion_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapp',
            name='title1',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='webapp',
            name='title2',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='sub_title1',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='sub_title2',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='tagline',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='writeup',
            field=models.TextField(blank=True),
        ),
    ]
